licenses(["notice"])  # BSD

package(default_visibility = ["//third_party/xmpmeta:xmpmeta_pkg"])

filegroup(
    name = "xmpmeta-headers",
    srcs = glob(["xmpmeta/*.h"]),
)

filegroup(
    name = "xdmlib-headers",
    srcs = glob(["xmpmeta/*.h"]),
)

filegroup(
    name = "jpeg_io_header",
    srcs = ["xmpmeta/jpeg_io.h"],
)

cc_library(
    name = "pano_meta_data",
    hdrs = ["xmpmeta/pano_meta_data.h"],
)

filegroup(
    name = "pano_meta_data_header",
    srcs = ["xmpmeta/pano_meta_data.h"],
)
